export type City = {
    slug: string;
    name: string;
    japaneseName: string;
    image: string;
    description: string;
    island: string;
    region: string;
    catchphrase: string;
    type: string;
    bestMonths: string[];
};

export const cities: City[] = [
    {
        name: "Tokyo",
        slug: "tokyo",
        japaneseName: "東京",
        image: "/cities/tokyo.webp",
        island: "Honshu",
        region: "Kanto",
        catchphrase: "The Imperial Gardens have opened the late wisteria.",
        type: "Metropolis",
        bestMonths: ["APR", "MAY", "OCT"],
        description: "Tokyo is the capital of Japan and the world's most populous metropolis, seamlessly blending ultramodern skyscrapers, neon-lit streets, and cutting-edge technology with traditional temples, shrines, and gardens."
    },
    {
        name: "Kyoto",
        slug: "kyoto",
        japaneseName: "京都",
        image: "/cities/kyoto.webp",
        island: "Honshu",
        region: "Kansai",
        catchphrase: "Bamboo grove at dawn — the light comes through in slow stripes.",
        type: "Old Capital",
        bestMonths: ["MAR", "APR", "NOV"],
        description: "Kyoto is the country's cultural and historical heart, often called its spiritual home. Located in a mountain-ringed basin, the city is renowned for its 2,000+ temples and shrines, traditional wooden machiya houses, exquisite gardens, and refined, 1,200-year-old culture."
    },
    {
        name: "Osaka",
        slug: "osaka",
        japaneseName: "大阪",
        image: "/cities/osaka.webp",
        island: "Honshu",
        region: "Kansai",
        catchphrase: "Street food smoke rises from Dotonbori before the crowds.",
        type: "Food City",
        bestMonths: ["MAR", "APR", "OCT", "NOV"],
        description: "Osaka is Japan's third-largest city and a vibrant, culinary-focused metropolis in the Kansai region known as the Nation's Kitchen. Famed for its outgoing locals, neon-lit nightlife, and street food like takoyaki, Osaka offers a relaxed, modern alternative to Tokyo, featuring major landmarks like Osaka Castle and Dotonbori."
    },
    {
        name: "Yokohama",
        slug: "yokohama",
        japaneseName: "横浜",
        image: "/cities/yokohama.webp",
        island: "Honshu",
        region: "Kanto",
        catchphrase: "The harbour lights shimmer through morning sea mist.",
        type: "Port City",
        bestMonths: ["APR", "MAY", "OCT"],
        description: "Yokohama is Japan's second-largest city and a major, historically significant port located just south of Tokyo in Kanagawa Prefecture. Renowned for its international flair, scenic waterfront, and the futuristic Minato Mirai 21 district, it offers a more relaxed, modern alternative to Tokyo while functioning as a key commercial hub."
    },
    {
        name: "Hiroshima",
        slug: "hiroshima",
        japaneseName: "広島",
        image: "/cities/hiroshima.webp",
        island: "Honshu",
        region: "Chugoku",
        catchphrase: "Peace descends at dusk over the memorial river.",
        type: "Peace City",
        bestMonths: ["MAR", "APR", "OCT", "NOV"],
        description: "Hiroshima is a powerful symbol of peace and resilience, rebuilt after the devastating 1945 atomic bombing into a thriving modern city. Its iconic Peace Memorial Park and Museum stand as solemn reminders of the past, while the nearby island of Miyajima with its famous floating torii gate draws visitors from around the world."
    },
    {
        name: "Nara",
        slug: "nara",
        japaneseName: "奈良",
        image: "/cities/nara.webp",
        island: "Honshu",
        region: "Kansai",
        catchphrase: "Sacred deer roam freely between ancient stone lanterns.",
        type: "Ancient Capital",
        bestMonths: ["MAR", "APR", "NOV"],
        description: "Nara is Japan's first permanent capital and a UNESCO World Heritage city, famous for its freely roaming sacred deer and monumental landmarks. Home to Todai-ji temple housing Japan's largest bronze Buddha, the vast Nara Park, and ancient Kasuga Taisha shrine."
    },
    {
        name: "Hakone",
        slug: "hakone",
        japaneseName: "箱根",
        image: "/cities/hakone.webp",
        island: "Honshu",
        region: "Kanto",
        catchphrase: "Lake Ashi gave a clear Fuji at 06:40 today.",
        type: "Spa Town",
        bestMonths: ["ALL YEAR"],
        description: "Hakone is a renowned mountain resort town in Kanagawa Prefecture, celebrated for its spectacular views of Mount Fuji, natural hot springs, and serene landscapes. A classic escape from Tokyo, it offers ryokan stays, the scenic Lake Ashi, open-air museums, and traditional crafts."
    },
    {
        name: "Nikko",
        slug: "nikko",
        japaneseName: "日光",
        image: "/cities/nikko.webp",
        island: "Honshu",
        region: "Kanto",
        catchphrase: "Tōshōgū cedars are wet with the morning fog.",
        type: "Mountain",
        bestMonths: ["MAY", "OCT", "NOV"],
        description: "Nikko is a mountainous UNESCO World Heritage town north of Tokyo, famous for its extraordinarily ornate Tosho-gu shrine complex. Surrounded by dense cedar forests, dramatic waterfalls, and serene Lake Chuzenji, it offers a striking contrast between lavish historic architecture and pristine natural scenery."
    },
    {
        name: "Naha",
        slug: "naha",
        japaneseName: "那覇",
        image: "/cities/naha.webp",
        island: "Okinawa",
        region: "Okinawa",
        catchphrase: "The scent of the sea drifts through Shuri's ancient stone gates.",
        type: "Island Capital",
        bestMonths: ["MAR", "APR", "MAY", "OCT", "NOV"],
        description: "Naha is the capital of Okinawa Prefecture and the cultural heart of the former Ryukyu Kingdom. Known for Shuri Castle, vibrant Kokusai Street, and a unique blend of Japanese and Ryukyuan traditions, it serves as the gateway to Okinawa's subtropical islands."
    },
    {
        name: "Nagoya",
        slug: "nagoya",
        japaneseName: "名古屋市",
        image: "/cities/nagoya.webp",
        island: "Honshu",
        region: "Chubu",
        catchphrase: "The castle keeps watch over a city that never stopped building.",
        type: "Castle City",
        bestMonths: ["MAR", "APR", "OCT", "NOV"],
        description: "Nagoya is Japan's fourth-largest city and a major industrial, historical, and transportation hub located in the center of Honshu. As the capital of Aichi Prefecture, it is famously the birthplace of the Toyota Motor Corporation and a center for manufacturing, including aerospace and ceramics."
    },
    {
        name: "Sapporo",
        slug: "sapporo",
        japaneseName: "札幌市",
        image: "/cities/sapporo.webp",
        island: "Hokkaido",
        region: "Hokkaido",
        catchphrase: "First snow of the season fell last night on the clock tower.",
        type: "Snow City",
        bestMonths: ["FEB", "JUL", "AUG"],
        description: "Sapporo is the capital of Japan's northernmost island, Hokkaido, and the nation's 4th largest city. Known for its snowy winters, renowned beer, and rich ramen culture, it is a hub of nature and urban life. Famous for hosting the 1972 Winter Olympics and the annual Snow Festival."
    },
    {
        name: "Fukuoka",
        slug: "fukuoka",
        japaneseName: "福岡市",
        image: "/cities/fukuoka.webp",
        island: "Kyushu",
        region: "Kyushu",
        catchphrase: "Yatai stalls line the river as evening settles in.",
        type: "Food & Port",
        bestMonths: ["MAR", "APR", "OCT", "NOV"],
        description: "Fukuoka is a vibrant, fast-growing coastal city on Japan's Kyushu island, serving as a historic gateway to Asia. Renowned for its relaxed atmosphere, rich culinary scene (especially tonkotsu ramen), and historic Hakata district, it perfectly blends modern urban life with traditional charm."
    },
    {
        name: "Kobe",
        slug: "kobe",
        japaneseName: "神戸",
        image: "/cities/kobe.webp",
        island: "Honshu",
        region: "Kansai",
        catchphrase: "Western facades catch the afternoon light above the harbour.",
        type: "Cosmopolitan",
        bestMonths: ["APR", "MAY", "OCT", "NOV"],
        description: "Kobe is a sophisticated port city nestled between the Rokko mountains and Osaka Bay, long renowned for its cosmopolitan atmosphere and international influences. Famous worldwide for its premium Kobe beef, stylish Kitano district with Western-style residences, and vibrant Chinatown."
    },
    {
        name: "Kamakura",
        slug: "kamakura",
        japaneseName: "鎌倉",
        image: "/cities/kamakura.webp",
        island: "Honshu",
        region: "Kanto",
        catchphrase: "The Great Buddha sits calm above the hydrangea paths.",
        type: "Coastal Temple",
        bestMonths: ["APR", "JUN", "SEP", "NOV"],
        description: "Kamakura is a coastal city south of Tokyo that served as Japan's political center during the 12th to 14th centuries. Renowned for its Great Buddha, numerous Zen temples, and scenic hiking trails through forested hills, it offers a perfect blend of history, spirituality, and natural beauty."
    },
    {
        name: "Kanazawa",
        slug: "kanazawa",
        japaneseName: "金沢",
        image: "/cities/kanazawa.webp",
        island: "Honshu",
        region: "Chubu",
        catchphrase: "Rain on the garden pond — Kenroku-en at its quietest.",
        type: "Craft City",
        bestMonths: ["APR", "MAY", "OCT", "NOV"],
        description: "Kanazawa is a beautifully preserved castle town on the Sea of Japan coast, often called Little Kyoto for its rich cultural heritage. Home to Kenroku-en, one of Japan's three great gardens, along with samurai and geisha districts and traditional crafts like Kutani porcelain and gold leaf."
    },
    {
        name: "Nagasaki",
        slug: "nagasaki",
        japaneseName: "長崎",
        image: "/cities/nagasaki.webp",
        island: "Kyushu",
        region: "Kyushu",
        catchphrase: "The hillside lanterns glow softly above the harbour at dusk.",
        type: "Historic Port",
        bestMonths: ["APR", "MAY", "OCT", "NOV"],
        description: "Nagasaki is a hilly, atmospheric port city with a uniquely cosmopolitan history as Japan's main gateway to the outside world during its period of isolation. Carrying the profound legacy of the 1945 atomic bombing, it also boasts a rich blend of Dutch, Chinese, and Portuguese influences."
    },
    {
        name: "Sendai",
        slug: "sendai",
        japaneseName: "仙台",
        image: "/cities/sendai.webp",
        island: "Honshu",
        region: "Tohoku",
        catchphrase: "Zelkova trees line the boulevard in deep autumn gold.",
        type: "Forest City",
        bestMonths: ["APR", "MAY", "OCT", "NOV"],
        description: "Sendai is the largest city in the Tohoku region and a vibrant modern metropolis known as the City of Trees for its zelkova-lined boulevards. Gateway to Matsushima bay and the nearby Zao mountains, it blends urban energy with easy access to nature and rich samurai heritage."
    },
    {
        name: "Matsuyama",
        slug: "matsuyama",
        japaneseName: "松山",
        image: "/cities/matsuyama.webp",
        island: "Shikoku",
        region: "Shikoku",
        catchphrase: "Steam rises from Dogo Onsen before the city wakes.",
        type: "Onsen Town",
        bestMonths: ["APR", "MAY", "OCT", "NOV"],
        description: "Matsuyama is the largest city on Shikoku island and home to one of Japan's finest original feudal castles. Famous for Dogo Onsen, one of the oldest hot spring bathhouses in Japan said to have inspired Studio Ghibli's Spirited Away, it exudes a relaxed, literary atmosphere."
    },
    {
        name: "Takayama",
        slug: "takayama",
        japaneseName: "高山",
        image: "/cities/takayama.webp",
        island: "Honshu",
        region: "Chubu",
        catchphrase: "Morning mist rolls over the Edo merchant quarter.",
        type: "Mountain Town",
        bestMonths: ["APR", "MAY", "OCT", "NOV"],
        description: "Takayama is a beautifully preserved Edo-period town nestled in the Japanese Alps of Gifu Prefecture. Its historic Sanmachi Suji merchant district, traditional sake breweries, vibrant morning markets, and proximity to the thatched-roof villages of Shirakawa-go make it one of Japan's most atmospheric destinations."
    },
    {
        name: "Kumamoto",
        slug: "kumamoto",
        japaneseName: "熊本",
        image: "/cities/kumamoto.webp",
        island: "Kyushu",
        region: "Kyushu",
        catchphrase: "The castle towers over cherry blossoms and morning mist.",
        type: "Castle Town",
        bestMonths: ["MAR", "APR", "OCT", "NOV"],
        description: "Kumamoto is a dynamic city on Kyushu island, home to one of Japan's most impressive feudal castles. Known for its spicy local cuisine, the beautiful Suizenji Jojuen garden, and as the gateway to the dramatic Aso volcanic caldera, it perfectly blends history and natural wonder."
    },
    {
        name: "Tsushima",
        slug: "tsushima",
        japaneseName: "対馬",
        image: "/cities/tsushima.webp",
        island: "Kyushu",
        region: "Kyushu",
        catchphrase: "Dense forest meets the sea at the edge of the known world.",
        type: "Island City",
        bestMonths: ["MAY", "JUN", "SEP", "OCT"],
        description: "Tsushima is a remote, rugged island in the Korea Strait, known for its pristine nature, dense forests, and rich samurai history. Famous as the setting of the legendary Battle of Tsushima and the popular video game Ghost of Tsushima, the island offers untouched landscapes and ancient shrines."
    },
    {
        name: "Nagano",
        slug: "nagano",
        japaneseName: "長野",
        image: "/cities/nagano.webp",
        island: "Honshu",
        region: "Chubu",
        catchphrase: "Snow monkeys soak in the onsen as flurries fall around them.",
        type: "Alpine City",
        bestMonths: ["JAN", "FEB", "MAY", "OCT"],
        description: "Nagano is a mountain city in central Honshu, renowned for hosting the 1998 Winter Olympics and as the gateway to the Japanese Alps. Famous for the snow monkeys of Jigokudani, the historic Zenko-ji temple, and world-class ski resorts like Hakuba and Shiga Kogen."
    },
    {
        name: "Beppu",
        slug: "beppu",
        japaneseName: "別府",
        image: "/cities/beppu.webp",
        island: "Kyushu",
        region: "Kyushu",
        catchphrase: "Steam from the Hells drifts across the cobalt blue pool.",
        type: "Onsen Capital",
        bestMonths: ["ALL YEAR"],
        description: "Beppu is Japan's hot spring capital on the island of Kyushu, producing more geothermal water than anywhere else in the country except Yellowstone. Famous for its eight 'Hells' — spectacular boiling pools of vivid colors — and its abundant onsen bathhouses, it is an unmissable destination for hot spring lovers."
    },
    {
        name: "Hatsukaichi",
        slug: "hatsukaichi",
        japaneseName: "廿日市",
        image: "/cities/hatsukaichi.webp",
        island: "Honshu",
        region: "Chugoku",
        catchphrase: "The floating torii emerges from the sea beneath sacred mountains.",
        type: "Gateway City",
        bestMonths: ["MAR", "APR", "OCT", "NOV"],
        description: "Hatsukaichi is a city in Hiroshima Prefecture best known as the gateway to Miyajima and the UNESCO-listed Itsukushima Shrine. Combining coastal scenery, historic temples, and access to sacred Mount Misen, it is one of western Japan's most iconic destinations."
    },
    {
        name: "Kochi",
        slug: "kochi",
        japaneseName: "高知",
        image: "/cities/kochi.webp",
        island: "Shikoku",
        region: "Shikoku",
        catchphrase: "Sunday market vendors arrange dried bonito under open skies.",
        type: "Market Town",
        bestMonths: ["MAR", "APR", "OCT", "NOV"],
        description: "Kochi is the capital of Kochi Prefecture on Shikoku island, known for its original feudal castle, vibrant Sunday market, and free-spirited local culture. Gateway to Cape Ashizuri and the rugged Shimanto River, the city is renowned for its bonito fish cuisine, warm climate, and lively Yosakoi festival."
    },
    {
        name: "Aomori",
        slug: "aomori",
        japaneseName: "青森",
        image: "/cities/aomori.webp",
        island: "Honshu",
        region: "Tohoku",
        catchphrase: "Nebuta lanterns cast warm light on cold northern faces.",
        type: "Festival City",
        bestMonths: ["AUG", "SEP", "OCT"],
        description: "Aomori is the northernmost major city on Honshu, famous for its spectacular Nebuta Festival featuring enormous illuminated floats, and as the gateway to the sacred Mount Osore and the pristine Shirakami-Sanchi UNESCO forest. Known for Japan's finest apples and fresh seafood from its cold northern waters."
    },
    {
        name: "Hirosaki",
        slug: "hirosaki",
        japaneseName: "弘前",
        image: "/cities/hirosaki.webp",
        island: "Honshu",
        region: "Tohoku",
        catchphrase: "Two thousand cherry trees surround the castle at full bloom.",
        type: "Cherry Town",
        bestMonths: ["APR", "MAY", "OCT"],
        description: "Hirosaki is a historic castle town in Aomori Prefecture, celebrated as one of Japan's premier cherry blossom destinations each spring. Its well-preserved Hirosaki Castle surrounded by over 2,500 cherry trees, along with Western-style Meiji-era architecture, traditional Tsugaru culture, and the backdrop of Mount Iwaki make it uniquely charming."
    },
    {
        name: "Matsumoto",
        slug: "matsumoto",
        japaneseName: "松本",
        image: "/cities/matsumoto.webp",
        island: "Honshu",
        region: "Chubu",
        catchphrase: "The black castle reflects in the moat against snow-capped peaks.",
        type: "Alpine Castle",
        bestMonths: ["APR", "MAY", "OCT", "NOV"],
        description: "Matsumoto is a gateway city to the Japanese Alps in Nagano Prefecture, home to Matsumoto Castle, one of Japan's most beautiful and best-preserved original feudal castles with its striking black exterior. Surrounded by the Northern Alps, it offers world-class mountaineering, pristine nature, and a vibrant arts scene."
    },
    {
        name: "Himeji",
        slug: "himeji",
        japaneseName: "姫路",
        image: "/cities/himeji.webp",
        island: "Honshu",
        region: "Kansai",
        catchphrase: "The White Heron soars above cherry petals in spring wind.",
        type: "Castle City",
        bestMonths: ["MAR", "APR", "OCT", "NOV"],
        description: "Himeji is home to Himeji Castle, widely considered Japan's most magnificent feudal castle and a UNESCO World Heritage Site. Known as the White Heron Castle for its brilliant white exterior, it survived both World War II and earthquakes intact, making it the finest surviving example of traditional Japanese castle architecture."
    },
    {
        name: "Kagoshima",
        slug: "kagoshima",
        japaneseName: "鹿児島",
        image: "/cities/kagoshima.webp",
        island: "Kyushu",
        region: "Kyushu",
        catchphrase: "Ash from Sakurajima dusts the rooftops by morning.",
        type: "Volcano City",
        bestMonths: ["MAR", "APR", "OCT", "NOV"],
        description: "Kagoshima is a vibrant southern city on Kyushu island, dramatically dominated by the active Sakurajima volcano rising from the bay. Often called the Naples of the Eastern world for its bay setting and volcanic backdrop, it is famous for its samurai heritage, black pork cuisine, shochu distilleries, and proximity to Yakushima island."
    },
    {
        name: "Nishinomiya",
        slug: "nishinomiya",
        japaneseName: "西宮市",
        image: "/cities/nishinomiya.webp",
        island: "Honshu",
        region: "Kansai",
        catchphrase: "The stadium roar echoes across the bay on summer evenings.",
        type: "Sports City",
        bestMonths: ["APR", "MAY", "SEP", "OCT"],
        description: "Nishinomiya is a city located in Hyogo Prefecture, an important commercial and shipping city in the Kansai region with the third largest population in Hyogo Prefecture. Nishinomiya is best known as the home of Koshien Stadium, where the Hanshin Tigers baseball team plays home games and where Japan's annual high school baseball championship is held."
    },
    {
        name: "Shirakawa",
        slug: "shirakawa",
        japaneseName: "白川村",
        image: "/cities/shirakawago.webp",
        island: "Honshu",
        region: "Chubu",
        catchphrase: "Thatched roofs disappear under a meter of fresh winter snow.",
        type: "Heritage Village",
        bestMonths: ["JAN", "FEB", "MAY", "OCT"],
        description: "Shirakawa-go is a UNESCO World Heritage mountainous village in Gifu Prefecture, famous for its extraordinary gassho-zukuri farmhouses with steep thatched roofs designed to withstand heavy snowfall. Particularly magical in winter when blanketed in deep snow, the village offers an immersive glimpse into rural Japanese life preserved across centuries."
    },
    {
        name: "Hakodate",
        slug: "hakodate",
        japaneseName: "函館",
        image: "/cities/hakodate.webp",
        island: "Hokkaido",
        region: "Hokkaido",
        catchphrase: "The night view from the mountain is worth every cold minute.",
        type: "Port & View",
        bestMonths: ["JUL", "AUG", "OCT", "NOV"],
        description: "Hakodate is a port city at the southern tip of Hokkaido, renowned for one of Japan's three greatest night views from Mount Hakodate, its historic Western-style buildings from the Meiji era, and its spectacular morning seafood market. A romantic, atmospheric city blending Japanese and foreign influences in a unique coastal setting."
    },
    {
        name: "Obihiro",
        slug: "obihiro",
        japaneseName: "帯広市",
        image: "/cities/obihiro.webp",
        island: "Hokkaido",
        region: "Hokkaido",
        catchphrase: "Hot air balloons rise above frozen Lake Shikaribetsu at dawn.",
        type: "Rural Hokkaido",
        bestMonths: ["JAN", "FEB", "JUL", "AUG"],
        description: "Obihiro is a city located in Tokachi Subprefecture, Hokkaido, Japan. Within Midorigaoka Park, Hokkaidoritsu Obihiro Museum displays etchings and modern prints, many by regional artists. Nearby, Obihiro Zoo is home to polar bears and Japanese macaques. Along the Tokachi River, Tokachigawa Onsen has natural hot springs."
    },
    {
        name: "Kurashiki",
        slug: "kurashiki",
        japaneseName: "倉敷",
        image: "/cities/kurashiki.webp",
        island: "Honshu",
        region: "Chugoku",
        catchphrase: "White-walled storehouses line a canal draped in willows.",
        type: "Canal Town",
        bestMonths: ["APR", "MAY", "OCT", "NOV"],
        description: "Kurashiki is a charming historic city in Okayama Prefecture, famous for its beautifully preserved Bikan Historical Quarter with white-walled storehouses lining a willow-draped canal. Home to the renowned Ohara Museum of Art — Japan's first Western art museum — it perfectly blends traditional aesthetics with a sophisticated cultural scene."
    },
    {
        name: "Yoshino",
        slug: "yoshino",
        japaneseName: "吉野",
        image: "/cities/yoshino.webp",
        island: "Honshu",
        region: "Kansai",
        catchphrase: "Thirty thousand cherry trees bloom up the mountain at once.",
        type: "Blossom Mountain",
        bestMonths: ["APR", "MAY"],
        description: "Yoshino is a sacred mountain town in Nara Prefecture and a UNESCO World Heritage Site, considered Japan's most celebrated cherry blossom destination with over 30,000 trees covering the mountainside. A place of deep spiritual significance in Japanese history and culture, it has been a pilgrimage site and imperial retreat for over a millennium."
    },
    {
        name: "Ito",
        slug: "ito",
        japaneseName: "伊東市",
        image: "/cities/ito.webp",
        island: "Honshu",
        region: "Kanto",
        catchphrase: "Izu Peninsula air — salt and pine and something quieter.",
        type: "Spa Resort",
        bestMonths: ["MAR", "APR", "OCT", "NOV"],
        description: "Ito is a city on central Japan's Izu Peninsula, renowned for its hot-spring resorts. In the center, the grand Tokaikan is a 1920s ryokan inn that's now a museum. Ikeda Museum of 20th Century Art has modern European painting and sculpture."
    },
    {
        name: "Atami",
        slug: "atami",
        japaneseName: "熱海",
        image: "/cities/atami.webp",
        island: "Honshu",
        region: "Kanto",
        catchphrase: "Retro ryokan lanterns glow above Sagami Bay at nightfall.",
        type: "Coastal Onsen",
        bestMonths: ["ALL YEAR"],
        description: "Atami is a popular hot spring resort city on the Izu Peninsula overlooking Sagami Bay, easily accessible from Tokyo. Long favored as a romantic getaway, it offers abundant onsen ryokan, the MOA Museum of Art with its stunning coastal views, fresh seafood, and a lively retro atmosphere."
    },
    {
        name: "Yakushima",
        slug: "yakushima",
        japaneseName: "屋久島",
        image: "/cities/yakushima.webp",
        island: "Kyushu",
        region: "Kyushu",
        catchphrase: "Ancient cedar forest — some trees have stood for seven thousand years.",
        type: "Wild Forest",
        bestMonths: ["MAY", "JUN", "SEP", "OCT"],
        description: "Yakushima is a town in Kagoshima Prefecture encompassing the entire UNESCO World Heritage island of the same name. Renowned for its ancient cedar forests, dramatic mountains, waterfalls, and unique ecosystem, it is one of Japan's most extraordinary natural destinations."
    },
]